const routes = {
  ROOT: "/",
  FILTERS: "/filters",
  AUTH: "/auth",
  USERS: "/users",
  REGISTER: "/register",
  IMAGE: "/image",
  LOGOUT: "/logout",
  KAKAO: "/kakao",
  KAKAO_CALLBACK: "/kakao/callback",
  NAVER: "/naver",
  NAVER_CALLBACK: "/naver/callback",
  NAVER_FAIL: "/naver/fail",
  GOOGLE: "/google",
  GOOGLE_CALLBACK: "/google/callback",
  OFFERS: "/offers",
  OFFER_ID: "/:offerId",
  OFFER_IMAGE: "/:offerId/image",
  OFFER_RECOMMEND: "/:offerId/recommend",
  OFFER_FULFILL: "/:offerId/fulfill",
  PRACTICE_HOUSES: "/practice-houses",
  HOUSE_ID: "/:houseId",
  HOUSE_IMAGE: "/:houseId/image",
  ROOM_IMAGES: "/:houseId/room-images",
  HOUSE_RECOMMEND: "/:houseId/recommend",
  HOUSE_FULFILL: "/:houseId/fulfill",
  COMMUNITY: "/community",
  POST_ID: "/:postId",
  POST_COMMENTS: "/:postId/comments",
  POST_COMMENT_ID: "/:postId/comments/:commentId",
};

export default routes;
